### ISSUE TITLE
Earthio Quarter 3, 2017 Priorities

### ISSUE THREAD

**Issue by PeterDSteinberg** [ContinuumIO/earthio#33]
## Earthio Quarter 3, 2017 Priorities
Let's address the checklist below in approximately the order shown, aiming to get this list done by AGU December. 
* [x] Continue work on transition of `load_array` and `load_meta` question #31
* [ ] Remove `attr`package use #29
* [ ] Address changes after xarray_filters changes and Elm PR 187 #28
* [ ] Use Grib files with xarray / earthio in progress #20
* [ ] Review / modify earthio/tif.py as it relates to xarray rasterio in progress #17
* [ ] Earth science data catalogue in progress #16
* [ ] Package for GIS / Earth science, e.g. coord transform, satellite utils ready #13
* [ ] Simplify earthio's readers - move to XArray data store back end class in progress #12
* [ ] Resolve NetCDF Python 2.7 issue seen in Travis #7
* [ ] EDIT (Nov 3) - Fix test failures resulting from xarray_filters refactor and changes to load_array -
 #35

### Docs / cleanup / promotion of Elm and related tools
* [ ] Documentation - status of Earthio and its relation of Elm/xarray/xarray_filters #32

cc @gbrener @hsparra
